name: aadivibes
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  catcher: ^0.6.9
  cupertino_icons: ^1.0.4
  dio: ^4.0.6
  encrypt: ^5.0.1
  firebase_auth: ^4.0.1
  firebase_core: ^2.0.0
  firebase_messaging: ^14.0.1
#  firebase_auth_oauth: any
#    git:
#      url: https://github.com/DharmaTech123/firebase_auth_oauth.git
#      path: firebase_auth_oauth
#      ref: main
  flutter:
    sdk: flutter
  flutter_local_notifications: any
  flutter_screenutil: ^5.5.3+2
  get: ^4.6.5
  get_storage: ^2.0.3
  google_sign_in: any
  logger: ^1.1.0
#  firebase_remote_config: 0.10.0+1
  path_provider: ^2.0.10
  pretty_dio_logger: ^1.2.0-beta-1
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  get_cli: ^1.8.1
  flutter_launcher_icons: ^0.11.0
  convex_bottom_bar: ^3.1.0+1
  syncfusion_flutter_sliders: ^20.3.58
  expandable_page_view: ^1.0.17
  just_audio: ^0.9.30
  flutter_easyloading: ^3.0.5
  country_code_picker: ^2.0.2
  url_launcher: ^6.1.6
  animated_splash_screen: ^1.3.0
  share_plus: any
  cloud_firestore: any
  image_picker: ^0.8.6
  pinput: ^2.2.21
dev_dependencies:
  flutter_test: 
    sdk: flutter

dependency_overrides:
  platform: ^3.1.0

flutter_icons:
  android: true
  ios: true
  min_sdk_android: 21
  image_path: 'assets/images/theme.png'

flutter: 
  assets: 
    - assets/locales/
    - assets/images/
  uses-material-design: true

